spring:
  application.name: spring-usboscilloscope
  profiles.active: development
#  profiles.active: production
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  # sql:
      # init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
        # data-locations: classpath:TRANSMITTER.sql
communicator-with-mcu-settings:
  default-serial-port-settings:
    name:
    baudRate: 115200
    dataBits: 6
    stopBits: 1
    parity: 0
    readTimeout: 10000
    writeTimeout: 0